"""
Dimensional Matcher for NopSCADlib Components

Extracts numeric dimensions from natural language prompts and matches them
against the NopSCADlib component catalog to find the exact type constant.

This is the reverse of generate_prompts.py: instead of converting
field_values → prompt, it converts prompt → field_values → type_constant.

Example:
    Prompt: "A ball bearing with 8mm bore, 22mm outer diameter, and 7mm width"
    Extracted: {bore: 8.0, od: 22.0, width: 7.0}
    Matched:   BB608 (bore=8, od=22, width=7) → confidence=0.99
"""

import re
import json
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple

# Path to the benchmark catalog (generated by enumerate_nopscadlib.py)
_CATALOG_PATHS = [
    Path(__file__).parent.parent.parent / "Text2CAD_SPM_2026" / "benchmark_ground_truth.json",
    Path(__file__).parent.parent.parent / "Text2CAD_SPM_2026" / "nopscadlib_component_catalog.json",
]


@dataclass
class DimensionalMatch:
    """Result of dimensional matching for a single component."""
    component_id: str           # e.g. "ball_bearing__BB608"
    type_constant: str          # e.g. "BB608"
    component_family: str       # e.g. "ball_bearing"
    module_function: str        # e.g. "ball_bearing"
    scad_call: str              # e.g. "ball_bearing(BB608);"
    confidence: float           # 0.0 to 1.0
    dimension_error: float      # Euclidean distance in dimension space
    matched_dimensions: Dict[str, float] = field(default_factory=dict)
    prompt_dimensions: Dict[str, float] = field(default_factory=dict)


@dataclass
class DimensionalMatchResult:
    """Result of dimensional matching on a prompt."""
    original_prompt: str
    detected_family: Optional[str] = None
    matches: List[DimensionalMatch] = field(default_factory=list)
    best_match: Optional[DimensionalMatch] = None
    has_match: bool = False

    def get_scad_code(self) -> Optional[str]:
        """Get OpenSCAD code for the best match."""
        if self.best_match:
            return (
                f"include <NopSCADlib/lib.scad>\n\n"
                f"{self.best_match.scad_call}"
            )
        return None


# =============================================================================
# CATALOG LOADER
# =============================================================================

_catalog_cache: Optional[Dict] = None


def _load_catalog() -> Dict:
    """Load the NopSCADlib component catalog (cached)."""
    global _catalog_cache
    if _catalog_cache is not None:
        return _catalog_cache

    for path in _CATALOG_PATHS:
        if path.exists():
            with open(path) as f:
                data = json.load(f)
            # benchmark_ground_truth.json has "components" list
            if "components" in data:
                _catalog_cache = data
                return _catalog_cache
            # nopscadlib_component_catalog.json has "families_summary" + individual entries
            if "families_summary" in data:
                _catalog_cache = data
                return _catalog_cache

    _catalog_cache = {"components": []}
    return _catalog_cache


def _get_components_by_family(family: str) -> List[Dict]:
    """Get all components in a family from the catalog."""
    catalog = _load_catalog()
    components = catalog.get("components", [])
    return [c for c in components if c.get("component_family") == family]


# =============================================================================
# DIMENSION EXTRACTION FROM PROMPTS (reverse of generate_prompts.py)
# =============================================================================

def _extract_numbers_with_labels(text: str) -> Dict[str, float]:
    """Extract labeled numeric dimensions from a prompt."""
    dims = {}

    # Common patterns: "Xmm bore", "X mm outer diameter", etc.
    patterns = [
        (r'([\d.]+)\s*mm\s*bore', 'bore'),
        (r'([\d.]+)\s*mm\s*outer\s*diameter', 'od'),
        (r'([\d.]+)\s*mm\s*(?:inner\s*)?(?:hole|inner\s*diameter)', 'bore'),
        (r'([\d.]+)\s*mm\s*width', 'width'),
        (r'([\d.]+)\s*mm\s*thick(?:ness)?', 'thickness'),
        (r'([\d.]+)\s*mm\s*flange\s*diameter', 'flange_dia'),
        (r'([\d.]+)\s*mm\s*face\s*width', 'face_width'),
        (r'([\d.]+)\s*mm\s*body\s*length', 'body_length'),
        (r'([\d.]+)\s*mm\s*(?:diameter\s*)?shaft', 'shaft_dia'),
        (r'([\d.]+)\s*mm\s*mounting\s*hole\s*spacing', 'hole_spacing'),
        (r'([\d.]+)\s*mm\s*(?:across\s*flats)', 'across_flats'),
        (r'for\s*([\d.]+)\s*mm\s*screws', 'screw_dia'),
        (r'([\d.]+)\s*mm\s*thread', 'screw_dia'),
        (r'([\d.]+)\s*mm\s*head\s*diameter', 'head_dia'),
        (r'head\s*height\s*([\d.]+)\s*mm', 'head_height'),
        (r'([\d.]+)\s*mm\s*diameter', 'diameter'),
        (r'([\d.]+)\s*mm\s*stator\s*diameter', 'stator_dia'),
        (r'([\d.]+)\s*mm\s*height', 'height'),
        (r'([\d.]+)\s*mm\s*length', 'length'),
        (r'([\d.]+)\s*mm\s*long', 'length'),
        (r'([\d.]+)\s*mm\s*tall', 'height'),
        (r'([\d.]+)\s*mm\s*wide', 'rail_width'),
        (r'([\d.]+)\s*mm\s*barrel\s*diameter', 'barrel_dia'),
        (r'([\d.]+)\s*mm\s*total\s*length', 'total_length'),
        (r'([\d.]+)\s*mm\s*body\s*diameter', 'body_dia'),
        (r'([\d.]+)\s*mm\s*pitch\s*diameter', 'pitch_dia'),
        (r'(\d+)\s*teeth', 'teeth'),
        (r'for\s*([\d.]+)\s*mm\s*(?:shaft|rod)', 'shaft_dia'),
        # LED-specific: "5mm through-hole LED" or "A 5.0mm through-hole LED"
        (r'([\d.]+)\s*mm\s*through-hole\s*led', 'led_dia'),
        (r'([\d.]+)\s*mm\s*led', 'led_dia'),
    ]

    for pattern, label in patterns:
        m = re.search(pattern, text, re.IGNORECASE)
        if m:
            try:
                dims[label] = float(m.group(1))
            except ValueError:
                pass

    # AxB pattern: "40mm x 40mm x 9.5mm" or "40.0mm x 40.0mm"
    axb = re.findall(r'([\d.]+)\s*mm\s*x\s*([\d.]+)\s*mm(?:\s*x\s*([\d.]+)\s*mm)?', text, re.IGNORECASE)
    if axb:
        dims['dim_x'] = float(axb[0][0])
        dims['dim_y'] = float(axb[0][1])
        if axb[0][2]:
            dims['dim_z'] = float(axb[0][2])

    # Block size pattern: "block size 40mm x 35mm"
    block = re.search(r'block\s*size\s*([\d.]+)\s*mm\s*x\s*([\d.]+)\s*mm', text, re.IGNORECASE)
    if block:
        dims['block_length'] = float(block.group(1))
        dims['block_width'] = float(block.group(2))

    return dims


def _detect_family_from_prompt(text: str) -> Optional[str]:
    """Detect component family from prompt text."""
    text_lower = text.lower()

    # Ordered from most specific to least specific
    family_patterns = [
        ("flanged ball bearing", "ball_bearing"),
        ("ball bearing", "ball_bearing"),
        ("linear bearing block", "bearing_block"),
        ("bearing block", "bearing_block"),
        ("linear bearing", "linear_bearing"),
        ("pillow block bearing", "pillow_block"),
        ("pillow block", "pillow_block"),
        ("penny washer", "washer"),
        ("rubber washer", "washer"),
        ("flat washer", "washer"),
        ("washer", "washer"),
        ("nylon-insert lock nut", "nut"),
        ("wing nut", "nut"),
        ("t-slot nut", "nut"),
        ("thin hex nut", "nut"),
        ("hex nut", "nut"),
        ("nut for", "nut"),
        ("nut with", "nut"),
        ("socket head cap screw", "screw"),
        ("countersunk screw", "screw"),
        ("dome head screw", "screw"),
        ("pan head screw", "screw"),
        ("hex head screw", "screw"),
        ("grub screw", "screw"),
        ("screw with", "screw"),
        ("stepper motor", "stepper_motor"),
        ("axial cooling fan", "fan"),
        ("brushless dc motor", "bldc_motor"),
        ("bldc motor", "bldc_motor"),
        ("timing pulley", "pulley"),
        ("hot end", "hot_end"),
        ("3d printer hot end", "hot_end"),
        ("linear guide rail", "rail"),
        ("linear rail", "rail"),
        ("aluminium extrusion", "extrusion"),
        ("extrusion profile", "extrusion"),
        ("heat-set insert", "insert"),
        ("threaded insert", "insert"),
        ("through-hole led", "led"),
        ("servo motor", "servo_motor"),
        ("shaft coupling", "shaft_coupling"),
        ("leadscrew nut", "leadnut"),
        ("centrifugal blower", "blower"),
        ("blower fan", "blower"),
        ("shaft support bracket", "sk_bracket"),
        ("iec power inlet", "iec"),
        ("display module", "display"),
        ("standoff pillar", "pillar"),
        ("battery cell", "batterie"),
        ("toggle switch", "toggle"),
        ("permanent magnet", "magnet"),
        ("mains transformer", "transformer"),
        ("solid state relay", "ssr"),
        ("pcb", "pcb"),
        ("printed circuit board", "pcb"),
        ("single-board computer", "pcb"),
        ("microcontroller", "pcb"),
        ("wifi", "pcb"),
        ("3d printer control board", "pcb"),
        ("3d printer mainboard", "pcb"),
    ]

    for pattern, family in family_patterns:
        if pattern in text_lower:
            return family
    return None


# =============================================================================
# PER-FAMILY DIMENSION MATCHING (reverse of generate_prompts.py field indices)
# =============================================================================

def _safe_float(val) -> Optional[float]:
    """Parse a field value to float."""
    if val is None:
        return None
    val = str(val).strip().strip('"').strip("'")
    try:
        return float(eval(val))
    except Exception:
        try:
            return float(val)
        except (ValueError, TypeError):
            return None


def _match_ball_bearing(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match ball bearing: fv[1]=bore, fv[2]=od, fv[3]=width, fv[7]=flange_dia."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    bore = _safe_float(fv[1])
    od = _safe_float(fv[2])
    width = _safe_float(fv[3])
    flange = _safe_float(fv[7]) if len(fv) > 7 else None

    if bore is not None:
        comp_dims['bore'] = bore
    if od is not None:
        comp_dims['od'] = od
    if width is not None:
        comp_dims['width'] = width
    if flange and flange > 0:
        comp_dims['flange_dia'] = flange

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_washer(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match washer: fv[1]=bore, fv[2]=od, fv[3]=thickness."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    bore = _safe_float(fv[1])
    od = _safe_float(fv[2])
    thk = _safe_float(fv[3])

    if bore is not None:
        comp_dims['bore'] = bore
    if od is not None:
        comp_dims['od'] = od
    if thk is not None:
        comp_dims['thickness'] = thk

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_nut(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match nut: fv[1]=screw_dia, fv[2]=across_flats, fv[3]=thickness."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    screw = _safe_float(fv[1])
    waf = _safe_float(fv[2])
    thk = _safe_float(fv[3])

    if screw is not None:
        comp_dims['screw_dia'] = screw
    if waf is not None:
        comp_dims['across_flats'] = waf
    if thk is not None:
        comp_dims['thickness'] = thk

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_screw(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match screw: fv[3]=dia, fv[4]=head_dia, fv[5]=head_height."""
    fv = comp.get("field_values", [])
    if len(fv) < 6:
        return float('inf'), {}

    comp_dims = {}
    dia = _safe_float(fv[3])
    head_dia = _safe_float(fv[4])
    head_h = _safe_float(fv[5])

    if dia is not None:
        comp_dims['diameter'] = dia
    if head_dia is not None:
        comp_dims['head_dia'] = head_dia
    if head_h is not None:
        comp_dims['head_height'] = head_h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_stepper_motor(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match stepper: fv[1]=side, fv[2]=length, fv[7]=shaft, fv[9]=holes."""
    fv = comp.get("field_values", [])
    if len(fv) < 3:
        return float('inf'), {}

    comp_dims = {}
    side = _safe_float(fv[1])
    length = _safe_float(fv[2])
    shaft = _safe_float(fv[7]) if len(fv) > 7 else None
    holes = _safe_float(fv[9]) if len(fv) > 9 else None

    if side is not None:
        comp_dims['face_width'] = side
    if length is not None:
        comp_dims['body_length'] = length
    if shaft is not None:
        comp_dims['shaft_dia'] = shaft
    if holes is not None:
        comp_dims['hole_spacing'] = holes

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_fan(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match fan: fv[0]=width, fv[1]=depth."""
    fv = comp.get("field_values", [])
    if len(fv) < 2:
        return float('inf'), {}

    comp_dims = {}
    w = _safe_float(fv[0])
    d = _safe_float(fv[1])

    if w is not None:
        comp_dims['dim_x'] = w
        comp_dims['dim_y'] = w  # fan is square: WxWxD
    if d is not None:
        comp_dims['dim_z'] = d

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_bldc_motor(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match BLDC motor: fv[1]=stator_dia, fv[2]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 3:
        return float('inf'), {}

    comp_dims = {}
    stator = _safe_float(fv[1])
    h = _safe_float(fv[2])

    if stator is not None:
        comp_dims['stator_dia'] = stator
    if h is not None:
        comp_dims['height'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_linear_bearing(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match linear bearing: fv[1]=length, fv[2]=od, fv[3]=bore."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    length = _safe_float(fv[1])
    od = _safe_float(fv[2])
    bore = _safe_float(fv[3])

    if bore is not None:
        comp_dims['bore'] = bore
    if od is not None:
        comp_dims['od'] = od
    if length is not None:
        comp_dims['length'] = length

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_bearing_block(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match bearing block: fv[1]=shaft, fv[4]=block_length, fv[5]=block_width."""
    fv = comp.get("field_values", [])
    if len(fv) < 6:
        return float('inf'), {}

    comp_dims = {}
    shaft = _safe_float(fv[1])
    blk_l = _safe_float(fv[4])
    blk_w = _safe_float(fv[5])

    if shaft is not None:
        comp_dims['shaft_dia'] = shaft
    if blk_l is not None:
        comp_dims['block_length'] = blk_l
    if blk_w is not None:
        comp_dims['block_width'] = blk_w

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_pcb(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match PCB: fv[2]=length, fv[3]=width, fv[4]=thickness."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    length = _safe_float(fv[2])
    width = _safe_float(fv[3])
    thickness = _safe_float(fv[4]) if len(fv) > 4 else None

    if length is not None:
        comp_dims['dim_x'] = length
    if width is not None:
        comp_dims['dim_y'] = width
    if thickness is not None:
        comp_dims['thickness'] = thickness

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_pulley(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match pulley: fv[2]=teeth, fv[3]=od (pitch diameter)."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    teeth = _safe_float(fv[2])
    od = _safe_float(fv[3])

    if teeth is not None:
        comp_dims['teeth'] = teeth
    if od is not None:
        comp_dims['pitch_dia'] = od

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_hot_end(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match hot end: fv[3]=total_length, fv[4]=barrel_dia."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    total_l = _safe_float(fv[3])
    barrel_d = _safe_float(fv[4])

    if total_l is not None:
        comp_dims['total_length'] = total_l
    if barrel_d is not None:
        comp_dims['barrel_dia'] = barrel_d

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_rail(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match rail: fv[1]=rail_width, fv[2]=rail_height."""
    fv = comp.get("field_values", [])
    if len(fv) < 3:
        return float('inf'), {}

    comp_dims = {}
    rw = _safe_float(fv[1])
    rh = _safe_float(fv[2])

    if rw is not None:
        comp_dims['rail_width'] = rw
    if rh is not None:
        comp_dims['height'] = rh

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_extrusion(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match extrusion: fv[1]=width, fv[2]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 3:
        return float('inf'), {}

    comp_dims = {}
    w = _safe_float(fv[1])
    h = _safe_float(fv[2])

    if w is not None:
        comp_dims['dim_x'] = w
    if h is not None:
        comp_dims['dim_y'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_insert(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match insert: fv[1]=od, fv[2]=length, fv[4]=screw_dia."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    od = _safe_float(fv[1])
    length = _safe_float(fv[2])
    screw = _safe_float(fv[4])

    if od is not None:
        comp_dims['od'] = od
        comp_dims['diameter'] = od  # alias
    if length is not None:
        comp_dims['length'] = length
    if screw is not None:
        comp_dims['screw_dia'] = screw

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_led(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match LED: fv[1]=diameter, fv[2]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 3:
        return float('inf'), {}

    comp_dims = {}
    dia = _safe_float(fv[1])
    h = _safe_float(fv[2])

    if dia is not None:
        comp_dims['diameter'] = dia
        comp_dims['led_dia'] = dia
    if h is not None:
        comp_dims['height'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_shaft_coupling(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match shaft coupling: fv[1]=length, fv[2]=od, fv[3]=bore1, fv[4]=bore2."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    length = _safe_float(fv[1])
    od = _safe_float(fv[2])
    bore1 = _safe_float(fv[3])
    bore2 = _safe_float(fv[4])

    if length is not None:
        comp_dims['length'] = length
    if od is not None:
        comp_dims['od'] = od
        comp_dims['diameter'] = od
    if bore1 is not None:
        comp_dims['bore'] = bore1
    if bore2 is not None:
        comp_dims['bore2'] = bore2

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_leadnut(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match leadnut: fv[2]=block_w, fv[3]=block_l, fv[4]=block_h."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    bw = _safe_float(fv[2])
    bl = _safe_float(fv[3])
    bh = _safe_float(fv[4])

    if bw is not None:
        comp_dims['dim_x'] = bw
    if bl is not None:
        comp_dims['dim_y'] = bl
    if bh is not None:
        comp_dims['dim_z'] = bh

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_blower(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match blower: fv[2]=width, fv[3]=depth, fv[4]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    w = _safe_float(fv[2])
    d = _safe_float(fv[3])
    h = _safe_float(fv[4])

    if w is not None:
        comp_dims['dim_x'] = w
    if d is not None:
        comp_dims['dim_y'] = d
    if h is not None:
        comp_dims['dim_z'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_sk_bracket(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match SK bracket: fv[1]=shaft_dia, fv[2]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 3:
        return float('inf'), {}

    comp_dims = {}
    shaft = _safe_float(fv[1])
    h = _safe_float(fv[2])

    if shaft is not None:
        comp_dims['shaft_dia'] = shaft
    if h is not None:
        comp_dims['height'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_pillow_block(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match pillow block: fv[1]=shaft, fv[3]=block_length, fv[4]=block_width."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    shaft = _safe_float(fv[1])
    bl = _safe_float(fv[3])
    bw = _safe_float(fv[4])

    if shaft is not None:
        comp_dims['shaft_dia'] = shaft
    if bl is not None:
        comp_dims['dim_x'] = bl
        comp_dims['block_length'] = bl
    if bw is not None:
        comp_dims['dim_y'] = bw
        comp_dims['block_width'] = bw

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_iec(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match IEC: fv[3]=width, fv[4]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    w = _safe_float(fv[3])
    h = _safe_float(fv[4])

    if w is not None:
        comp_dims['dim_x'] = w
    if h is not None:
        comp_dims['dim_y'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_display(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match display: fv[2]=width, fv[3]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    w = _safe_float(fv[2])
    h = _safe_float(fv[3])

    if w is not None:
        comp_dims['dim_x'] = w
    if h is not None:
        comp_dims['dim_y'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_pillar(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match pillar: fv[2]=screw_dia, fv[3]=length, fv[4]=od."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    screw = _safe_float(fv[2])
    length = _safe_float(fv[3])
    od = _safe_float(fv[4])

    if screw is not None:
        comp_dims['screw_dia'] = screw
    if length is not None:
        comp_dims['length'] = length
    if od is not None:
        comp_dims['diameter'] = od

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_battery(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match battery: fv[2]=height, fv[3]=diameter."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    h = _safe_float(fv[2])
    d = _safe_float(fv[3])

    if h is not None:
        comp_dims['height'] = h
    if d is not None:
        comp_dims['diameter'] = d

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_toggle(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match toggle: fv[2]=body_dia, fv[3]=body_height."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    bd = _safe_float(fv[2])
    bh = _safe_float(fv[3])

    if bd is not None:
        comp_dims['body_dia'] = bd
        comp_dims['diameter'] = bd
    if bh is not None:
        comp_dims['height'] = bh

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_magnet(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match magnet: fv[2]=diameter, fv[3]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 4:
        return float('inf'), {}

    comp_dims = {}
    d = _safe_float(fv[2])
    h = _safe_float(fv[3])

    if d is not None:
        comp_dims['diameter'] = d
    if h is not None:
        comp_dims['height'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_transformer(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match transformer: fv[2]=length, fv[3]=width, fv[4]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    l = _safe_float(fv[2])
    w = _safe_float(fv[3])
    h = _safe_float(fv[4])

    if l is not None:
        comp_dims['dim_x'] = l
    if w is not None:
        comp_dims['dim_y'] = w
    if h is not None:
        comp_dims['dim_z'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


def _match_ssr(prompt_dims: Dict, comp: Dict) -> Tuple[float, Dict]:
    """Match SSR: fv[2]=length, fv[3]=width, fv[4]=height."""
    fv = comp.get("field_values", [])
    if len(fv) < 5:
        return float('inf'), {}

    comp_dims = {}
    l = _safe_float(fv[2])
    w = _safe_float(fv[3])
    h = _safe_float(fv[4])

    if l is not None:
        comp_dims['dim_x'] = l
    if w is not None:
        comp_dims['dim_y'] = w
    if h is not None:
        comp_dims['dim_z'] = h

    return _compute_dimension_error(prompt_dims, comp_dims), comp_dims


# Family → matcher function dispatch table
FAMILY_MATCHERS = {
    "ball_bearing": _match_ball_bearing,
    "washer": _match_washer,
    "nut": _match_nut,
    "screw": _match_screw,
    "stepper_motor": _match_stepper_motor,
    "fan": _match_fan,
    "bldc_motor": _match_bldc_motor,
    "linear_bearing": _match_linear_bearing,
    "bearing_block": _match_bearing_block,
    "pcb": _match_pcb,
    "pulley": _match_pulley,
    "hot_end": _match_hot_end,
    "rail": _match_rail,
    "extrusion": _match_extrusion,
    "insert": _match_insert,
    "led": _match_led,
    "shaft_coupling": _match_shaft_coupling,
    "leadnut": _match_leadnut,
    "blower": _match_blower,
    "sk_bracket": _match_sk_bracket,
    "pillow_block": _match_pillow_block,
    "iec": _match_iec,
    "display": _match_display,
    "pillar": _match_pillar,
    "batterie": _match_battery,
    "toggle": _match_toggle,
    "magnet": _match_magnet,
    "transformer": _match_transformer,
    "ssr": _match_ssr,
}


# =============================================================================
# CORE MATCHING LOGIC
# =============================================================================

def _compute_dimension_error(prompt_dims: Dict[str, float], comp_dims: Dict[str, float]) -> float:
    """
    Compute Euclidean distance between prompt dimensions and component dimensions.
    Only compares dimensions that appear in BOTH sets.
    Returns infinity if no overlap.
    """
    # Find common dimension keys
    common_keys = set(prompt_dims.keys()) & set(comp_dims.keys())
    if not common_keys:
        return float('inf')

    # Compute relative error for each common dimension
    errors = []
    for key in common_keys:
        p_val = prompt_dims[key]
        c_val = comp_dims[key]
        if c_val == 0 and p_val == 0:
            errors.append(0.0)
        elif c_val == 0:
            errors.append(abs(p_val))
        else:
            # Relative error
            errors.append(abs(p_val - c_val) / max(abs(c_val), 1e-6))

    if not errors:
        return float('inf')

    # Return mean relative error
    return sum(errors) / len(errors)


def _error_to_confidence(error: float, n_matched: int, n_total_prompt: int) -> float:
    """
    Convert dimension error to confidence score.

    Args:
        error: Mean relative error (0 = perfect match)
        n_matched: Number of dimensions that matched
        n_total_prompt: Total dimensions in the prompt

    Returns:
        Confidence in [0, 1]
    """
    if error == float('inf') or n_matched == 0:
        return 0.0

    # Base confidence from error: perfect match → 0.99, 10% error → 0.85
    if error < 0.001:
        base = 0.99
    elif error < 0.01:
        base = 0.95
    elif error < 0.05:
        base = 0.90
    elif error < 0.10:
        base = 0.85
    elif error < 0.20:
        base = 0.70
    else:
        base = max(0.3, 1.0 - error)

    # Bonus for matching more dimensions
    coverage = n_matched / max(n_total_prompt, 1)
    coverage_bonus = coverage * 0.05  # Up to 5% bonus for full coverage

    return min(base + coverage_bonus, 0.99)


def match_prompt_to_component(prompt: str) -> DimensionalMatchResult:
    """
    Match a natural language prompt to a NopSCADlib component using dimensions.

    This is the main entry point. It:
    1. Detects the component family from the prompt
    2. Extracts numeric dimensions
    3. Searches all components in that family
    4. Returns the best match with confidence

    Args:
        prompt: Natural language prompt (anonymized, no model numbers)

    Returns:
        DimensionalMatchResult with best match and alternatives
    """
    result = DimensionalMatchResult(original_prompt=prompt)

    # Step 1: Detect family
    family = _detect_family_from_prompt(prompt)
    if not family:
        return result
    result.detected_family = family

    # Step 2: Extract dimensions from prompt
    prompt_dims = _extract_numbers_with_labels(prompt)
    if not prompt_dims:
        return result

    # Step 3: Get matcher for this family
    matcher = FAMILY_MATCHERS.get(family)
    if not matcher:
        return result

    # Step 4: Search all components in this family
    candidates = _get_components_by_family(family)
    if not candidates:
        return result

    matches = []
    for comp in candidates:
        error, comp_dims = matcher(prompt_dims, comp)
        if error == float('inf'):
            continue

        # Compute confidence
        common_keys = set(prompt_dims.keys()) & set(comp_dims.keys())
        confidence = _error_to_confidence(error, len(common_keys), len(prompt_dims))

        match = DimensionalMatch(
            component_id=comp.get("id", ""),
            type_constant=comp.get("type_constant", ""),
            component_family=family,
            module_function=comp.get("module_function", ""),
            scad_call=comp.get("scad_call", ""),
            confidence=confidence,
            dimension_error=error,
            matched_dimensions=comp_dims,
            prompt_dimensions=prompt_dims,
        )
        matches.append(match)

    # Sort by error (ascending) → best match first
    matches.sort(key=lambda m: m.dimension_error)
    result.matches = matches

    if matches:
        result.best_match = matches[0]
        result.has_match = matches[0].confidence >= 0.70

    return result


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

def match_and_get_scad(prompt: str) -> Optional[str]:
    """
    Match a prompt and return the OpenSCAD code if confident.

    Args:
        prompt: Natural language prompt

    Returns:
        OpenSCAD code string or None
    """
    result = match_prompt_to_component(prompt)
    if result.has_match:
        return result.get_scad_code()
    return None


def get_type_constant(prompt: str) -> Optional[str]:
    """
    Match a prompt and return just the type constant name.

    Args:
        prompt: Natural language prompt

    Returns:
        Type constant string (e.g., "BB608") or None
    """
    result = match_prompt_to_component(prompt)
    if result.has_match:
        return result.best_match.type_constant
    return None
